id: P009247
initial_creation_type: ocr
source_metadata:
  id: bdr:W21016
  title: གངས་ལྗོངས་རིག་གནས
  author: ''
  volumes:
    18e378dc380d42feb602964c328a96a1:
      image_group_id: I2DB57318
      title: ''
      volume_number: 1
      total_pages: 82
    98b221fe995a407d8dfe83d737b7483f:
      image_group_id: I2DB57319
      title: ''
      volume_number: 2
      total_pages: 102
    ead60885b0a1452d910096082c7ba163:
      image_group_id: I2DB57320
      title: ''
      volume_number: 3
      total_pages: 94
    dfd128800b814ac38c3dd850d898c1ee:
      image_group_id: I2DB57321
      title: ''
      volume_number: 4
      total_pages: 98
    c1df932cc2294ddfb0ef01e46ec87ec0:
      image_group_id: I2DB57322
      title: ''
      volume_number: 5
      total_pages: 94
    cdc89544dfbb4e08a4d99c82da664ae2:
      image_group_id: I2DB57323
      title: ''
      volume_number: 6
      total_pages: 94
    03143085c8924161bca94e56221e0713:
      image_group_id: I2DB57324
      title: ''
      volume_number: 7
      total_pages: 88
    7ad7fca764aa40acb552988d25d3e944:
      image_group_id: I2DB57325
      title: ''
      volume_number: 8
      total_pages: 94
    fa8558a4875244fb8192b20a75dc4923:
      image_group_id: I2DB57326
      title: ''
      volume_number: 9
      total_pages: 98
    a05d2f293fae4769b0f398a5b42b6363:
      image_group_id: I2DB57327
      title: ''
      volume_number: 10
      total_pages: 98
    20a50c3e5a3a418ab60b8b1b33345c6c:
      image_group_id: I2DB57328
      title: ''
      volume_number: 11
      total_pages: 108
    fd3aaafb43024efbb285844ce22ea73d:
      image_group_id: I2DB57329
      title: ''
      volume_number: 12
      total_pages: 110
    3b6edbd144064517aaba52dcef0a6373:
      image_group_id: I2DB57330
      title: ''
      volume_number: 13
      total_pages: 110
    a1f239bd02564010a8c5c0ee091524fc:
      image_group_id: I2DB57331
      title: ''
      volume_number: 14
      total_pages: 118
    b2a7c59d558e4ace9b4161b0b08c2ab9:
      image_group_id: I2DB57332
      title: ''
      volume_number: 15
      total_pages: 110
    cc91531379f64cb78810b322692445a2:
      image_group_id: I2DB57333
      title: ''
      volume_number: 16
      total_pages: 106
    98bc1ed0f367421b8eb96e27c203d734:
      image_group_id: I2DB57334
      title: ''
      volume_number: 17
      total_pages: 98
    ba819d5b26cc499d945e613391fbbb86:
      image_group_id: I2DB57335
      title: ''
      volume_number: 18
      total_pages: 104
    6097828a26e349c99f80f7facb32bdb9:
      image_group_id: I2DB57336
      title: ''
      volume_number: 19
      total_pages: 116
    72d3ce59455f42258e3905c6a9ecce9c:
      image_group_id: I2DB57337
      title: ''
      volume_number: 20
      total_pages: 110
    76bafb4e461b4d05a3b4643c6f7183da:
      image_group_id: I2DB57338
      title: ''
      volume_number: 21
      total_pages: 72
    3fc54a50125641c394be474a00211ba3:
      image_group_id: I2DB57339
      title: ''
      volume_number: 22
      total_pages: 114
    f838c2f2c804444997925dc3b777484b:
      image_group_id: I2DB57340
      title: ''
      volume_number: 23
      total_pages: 106
    fdd223d6a3f34c39ad600a4bee79b07d:
      image_group_id: I2DB57341
      title: ''
      volume_number: 24
      total_pages: 114
    adf59c4971d04be2930dd896aa204e34:
      image_group_id: I2DB57342
      title: ''
      volume_number: 25
      total_pages: 120
    1e83991788ba411e91446cef223eb5c1:
      image_group_id: I2DB57343
      title: ''
      volume_number: 26
      total_pages: 110
    4b5d2b6022144df19f9d87638526f0c0:
      image_group_id: I2DB57344
      title: ''
      volume_number: 27
      total_pages: 118
    bbc47268ad6a4a6d9e8acad7cf9d209d:
      image_group_id: I2DB57345
      title: ''
      volume_number: 28
      total_pages: 112
    51bb50d5149a44eca2bd696c64c8b2ad:
      image_group_id: I2DB57346
      title: ''
      volume_number: 29
      total_pages: 94
    958f28573dc344afb445a9e93b769cd5:
      image_group_id: I2DB57347
      title: ''
      volume_number: 30
      total_pages: 110
    282c3cbd644445c9a4a69e8ed32f2fa4:
      image_group_id: I2DB57348
      title: ''
      volume_number: 31
      total_pages: 114
    609358bab1264d2e99e681ca0a1bd221:
      image_group_id: I2DB57349
      title: ''
      volume_number: 32
      total_pages: 110
    81940c69a759456190035f7525f472d7:
      image_group_id: I2DB57350
      title: ''
      volume_number: 33
      total_pages: 110
    e850b856579747709c35c8075ae877df:
      image_group_id: I2DB57351
      title: ''
      volume_number: 34
      total_pages: 124
    1b709cfc924c43039da676b736327cfe:
      image_group_id: I2DB57352
      title: ''
      volume_number: 35
      total_pages: 110
    5aad3fe9c44e4f069a805dff241b582c:
      image_group_id: I2DB57353
      title: ''
      volume_number: 36
      total_pages: 110
    e95819020c124f4fbdddc6b98f28f735:
      image_group_id: I2DB57354
      title: ''
      volume_number: 37
      total_pages: 110
    64fc34aad85643cca46f4a3c506a1548:
      image_group_id: I2DB57355
      title: ''
      volume_number: 38
      total_pages: 118
    fe35b30a55e5421bad4aa8a9cfb619ce:
      image_group_id: I2DB57356
      title: ''
      volume_number: 39
      total_pages: 110
    8366850dbdc049ea9cd544831ea557e5:
      image_group_id: I2DB57357
      title: ''
      volume_number: 40
      total_pages: 110
    3525ed93269b4cc282752a218a18fc79:
      image_group_id: I2DB57358
      title: ''
      volume_number: 41
      total_pages: 110
    9b83e9c8bccf46949d2abadd7e455ec0:
      image_group_id: I2DB57359
      title: ''
      volume_number: 42
      total_pages: 110
    32abeedfc36f45a59d6506d679801853:
      image_group_id: I2DB57360
      title: ''
      volume_number: 43
      total_pages: 110
    3d167753556644c7a147794e3f8e457f:
      image_group_id: I2DB57361
      title: ''
      volume_number: 44
      total_pages: 110
    58022be32b2d4830a7089911509113ac:
      image_group_id: I2DB57362
      title: ''
      volume_number: 45
      total_pages: 110
    844dccecad284743aabae2812bef1d05:
      image_group_id: I2DB57363
      title: ''
      volume_number: 46
      total_pages: 110
    dc83947cb8ca4616b3a22f9a8bca72c1:
      image_group_id: I2DB57364
      title: ''
      volume_number: 47
      total_pages: 110
    973bfd0a1ac5426a8a0f6c0a15e8307c:
      image_group_id: I2DB57365
      title: ''
      volume_number: 48
      total_pages: 110
    5e167017197a4257983dc523796985c8:
      image_group_id: I2DB57366
      title: ''
      volume_number: 49
      total_pages: 110
    efaeef0a11874f1292fb91ee9cceb6ba:
      image_group_id: I2DB57367
      title: ''
      volume_number: 50
      total_pages: 110
    18b76612b0014f85b7e82b1167c71d39:
      image_group_id: I2DB57368
      title: ''
      volume_number: 51
      total_pages: 110
    6bb0666663c84c70a16544cc66935808:
      image_group_id: I2DB57369
      title: ''
      volume_number: 52
      total_pages: 112
    1b4400675df343e3aa96389be29cce17:
      image_group_id: I2DB57370
      title: ''
      volume_number: 53
      total_pages: 110
    d278035ee7cb4c3d8bdbfda03fe7d361:
      image_group_id: I2DB57371
      title: ''
      volume_number: 54
      total_pages: 110
    484cb1081aaa414da6495bd58205b78a:
      image_group_id: I2DB57372
      title: ''
      volume_number: 55
      total_pages: 110
    4a71c2f0ad5f48a1a8b4c29455fdb52c:
      image_group_id: I2DB57373
      title: ''
      volume_number: 56
      total_pages: 0
    553511c66f5e479180087e3502722d91:
      image_group_id: I2DB57374
      title: ''
      volume_number: 57
      total_pages: 118
    ed56a74a04f7493a92a5733273448646:
      image_group_id: I2DB57375
      title: ''
      volume_number: 58
      total_pages: 0
    9b87c12908eb4e73829f7f08b8a29bbb:
      image_group_id: I2DB57376
      title: ''
      volume_number: 59
      total_pages: 110
    b0a926e2c20d4a11bb2a2e1de3a02840:
      image_group_id: I2DB57377
      title: ''
      volume_number: 60
      total_pages: 0
    88a13378608f4c96850c033aab9f07ac:
      image_group_id: I2DB57378
      title: ''
      volume_number: 61
      total_pages: 0
    212bfb5969e74c5b9debe926dd7d3b01:
      image_group_id: I2DB57379
      title: ''
      volume_number: 62
      total_pages: 0
    ddb093b5881647659527d736500850df:
      image_group_id: I2DB57380
      title: ''
      volume_number: 63
      total_pages: 0
    fd84cb3ddfa4488eb8ea94a60cd32b06:
      image_group_id: I2DB57381
      title: ''
      volume_number: 64
      total_pages: 0
    3da7b561d8084696b6bd123c66267e7b:
      image_group_id: I2DB57382
      title: ''
      volume_number: 65
      total_pages: 0
    d277d306db2c41cf957596fb3fc9fcc1:
      image_group_id: I2DB57383
      title: ''
      volume_number: 66
      total_pages: 0
    2bd00c2dc73e4cfdb0a0dbf3cfb5999b:
      image_group_id: I2DB57384
      title: ''
      volume_number: 67
      total_pages: 0
    2095736fac5543f798bfd07a535e3204:
      image_group_id: I2DB57385
      title: ''
      volume_number: 68
      total_pages: 0
    626edd7f03a34bb4a5aeff66897cd74f:
      image_group_id: I2DB57386
      title: ''
      volume_number: 69
      total_pages: 0
    599d78f9f06d4201986df45dcbff2028:
      image_group_id: I2DB57387
      title: ''
      volume_number: 70
      total_pages: 0
    ba420a13a8da4464b1878ccc7781797e:
      image_group_id: I2DB57388
      title: ''
      volume_number: 71
      total_pages: 0
    491422b8572b4ec0902ddcf34d0f4f34:
      image_group_id: I2DB57389
      title: ''
      volume_number: 72
      total_pages: 0
    eea82ee0b85e4ee08f95345b493df6a1:
      image_group_id: I2DB57390
      title: ''
      volume_number: 73
      total_pages: 0
    e6237b54ed8d40e78e43f1717673c09b:
      image_group_id: I2DB57391
      title: ''
      volume_number: 74
      total_pages: 0
    af8e8b6942d24bbb904e111c4a4e8016:
      image_group_id: I2DB57392
      title: ''
      volume_number: 75
      total_pages: 0
    0eb80170924d4a7a95310e011ee76684:
      image_group_id: I2DB57393
      title: ''
      volume_number: 76
      total_pages: 0
    0a0555176e28420fa5da39c20bb36ebe:
      image_group_id: I2DB57394
      title: ''
      volume_number: 77
      total_pages: 0
    bebbcdd851c8419090626171394428cc:
      image_group_id: I2DB57395
      title: ''
      volume_number: 78
      total_pages: 0
    4ebc28238df14101830eba66c19af732:
      image_group_id: I2DB57396
      title: ''
      volume_number: 79
      total_pages: 0
    d5e028c4f001410cb4a1e2302b4d685e:
      image_group_id: I2DB57397
      title: ''
      volume_number: 80
      total_pages: 0
